[package]
name = "chip8"
version = "0.1.0"
authors = ["Bryce Davis <me@bryceadavis.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rand = "0.7.0"
fps_clock = "2.0"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["gfx"]
